# Generated by Django 4.0.5 on 2022-06-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_point', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='datas',
        ),
    ]
