# Generated by Django 4.0.5 on 2022-06-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_point', '0002_rename_data_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
