# Generated by Django 4.0.5 on 2022-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_point', '0004_course_dtls'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_dtls',
            name='slug',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
