# Generated by Django 4.0.5 on 2022-07-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_point', '0005_course_dtls_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('s_no', models.IntegerField()),
                ('video_id', models.CharField(max_length=200)),
                ('is_preview', models.BooleanField(default=False)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.course_dtls')),
            ],
        ),
    ]
