# Generated by Django 4.0.5 on 2022-07-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_point', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.course_dtls')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.datas')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.course_dtls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.datas')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.usercourse')),
            ],
        ),
    ]
