# Generated by Django 4.0.5 on 2022-07-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_point', '0008_alter_payment_user_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.course_dtls')),
            ],
        ),
    ]
