# Generated by Django 4.0.5 on 2022-07-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_point', '0009_refcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='pre_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.course_dtls')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial_point.course_dtls')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
